// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class catagory_validation_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catagory_validation_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "202304091800102_catagory_validation_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
