//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSubmission.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DotNetUser
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Name should not be empty!")]
        [StringLength(10, ErrorMessage = "Name should not be exceed 10 characters!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please select your gender!")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Please select your Profession!")]
        public string Profession { get; set; }

        [Required(ErrorMessage = "Please select your hobbies!")]
        public string[] Hobbies { get; set; }

        [Required(ErrorMessage = "Please provide your date of birth!")]
        public string DOB { get; set; }

        [Required(ErrorMessage = "Password should not be empty!")]
        [MinLength(6, ErrorMessage = "Password should be minimum 6 characters")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Retype your password again!")]
        [Compare("Password", ErrorMessage = "Password does not matched!")]
        public string RePassword { get; set; }
    }
}
